name: 'dbt_transform'
version: '1.0.0'
profile: 'dbt_transform'

model-paths: ["models"]
macro-paths: ["macros"]

clean-targets:
  - "target"
  - "dbt_packages"


models:
  dbt_transform:
    staging:
      +materialized: view
    intermediate:
      +materialized: view
    marts:
      +materialized: table

vars:
  use_demo_data: false
